name: pubnub-agent
version: 1.1
summary: cloud pubnub agent
description: >
    sends and receive messages from cloud pubnub server
confinement: devmode
grade: stable
            
apps:
  pubnub-agent:
    command: 'sh $SNAP/start.sh' 
    plugs: [network, network-control]

parts:
  pubnub-agent:
    plugin: python
  move:
    plugin: dump
    source: .

architectures: [armhf amd64]
